server:
  port: 9090


eureka:
  client:
    serviceUrl:
      defaultZone: http://47.98.189.37:20280/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

skyler:
  kafka:
    config:
      producer:
        topic: feign-info
        brokers:
          - 47.98.189.37:9092

