eureka:
  client:
    serviceUrl:
      defaultZone: http://47.98.189.37:20282/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

DATABASE_HOST: localhost
DATABASE_PORT: 3306
DATABASE_NAME: server_info
DATABASE_USER: root
DATABASE_PASSWORD: root123