server:
  port: 9092


skyler:
  kafka:
    config:
      consumer:
        topic: feign-info
        #        brokers:
        #          - 1.2.3.4:9092
        group-id: feign-info-group-id

spring:
  kafka:
    consumer:
      bootstrap-servers: 1.2.3.4:9092
      group-id: feign-info-group-id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?allowMultiQueries=true&allowPublicKeyRetrieval=true&useSSL=false
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
    # Number of ms to wait before throwing an exception if no connection is available.
    tomcat:
      max-wait: 10000
      # Maximum number of active connections that can be allocated from this pool at the same time.
      max-active: 50
      # Validate the connection before borrowing it from the pool.
      test-on-borrow: true

mybatis:
  ## Locations of Mapper xml config file
  mapperLocations: classpath*:com/skyler/**/mapper/*.xml
